plugin interface constructed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -721,6 +721,9 @@ EOF
   libs_qga="-lws2_32 -lwinmm -lpowrprof $libs_qga"
 fi
 
+
+vine_path=""
+proj_name=""
 werror=""
 
 for opt do
@@ -976,6 +979,10 @@ for opt do
   --enable-pie) pie="yes"
   ;;
   --disable-pie) pie="no"
+  ;;
+  --vine-path=*) vine_path="$optarg"
+  ;;
+  --proj-name=*) proj_name="$optarg"
   ;;
   --enable-werror) werror="yes"
   ;;
@@ -4597,6 +4604,55 @@ echo "VERSION=$qemu_version" >>$config_host_mak
 echo "PKGVERSION=$pkgversion" >>$config_host_mak
 echo "SRC_PATH=$source_path" >> $config_host_mak
 echo "TARGET_DIRS=$target_list" >> $config_host_mak
+
+echo "VINE_PATH=$vine_path" >> $config_host_mak
+echo "PROJECT_NAME=$proj_name" >> $config_host_mak
+
+proj_path="$source_path/$proj_name"
+
+if test -z $proj_name; then
+  echo "Error: You must specify a project name"
+  echo "Example: --proj-name=tracecap"
+  exit 1
+
+elif test "$proj_name" = "sample_plugin"; then
+  echo "#define TEMU_HOME \"$source_path\"" >> $config_host_mak
+  echo "#define PROJECT_HOME \"$proj_path\"" >> $config_host_mak
+  echo "#define TAINT_ENABLED 1" >> $config_host_mak
+  echo "#define DEFINE_INSN_BEGIN" >> $config_host_mak
+  echo "#define DEFINE_BLOCK_BEGIN" >> $config_host_mak
+  echo "#define TAINTCHECK_CLEAR_ZERO" >> $config_host_mak
+  echo "#define PLUGIN_SAMPLE" >> $config_host_mak
+
+elif test "$proj_name" = "tracecap"; then
+  echo "#define TEMU_HOME \"$source_path\"" >> $config_host_mak
+  echo "#define PROJECT_HOME \"$proj_path\"" >> $config_host_mak
+  echo "#define TAINT_ENABLED 1" >> $config_host_mak
+  echo "#define DEFINE_BLOCK_BEGIN" >> $config_host_mak
+  echo "#define DEFINE_INSN_BEGIN" >> $config_host_mak    
+  echo "#define DEFINE_INSN_END" >> $config_host_mak    
+  echo "#define DEFINE_EIP_TAINTED" >> $config_host_mak    
+  echo "#define TAINT_FLAGS 1" >> $config_host_mak    
+  echo "#define PRECISE_EFLAGS" >> $config_host_mak
+  echo "#define PLUGIN_TRACECAP" >> $config_host_mak
+
+elif test "$proj_name" = ""; then
+  echo "#define TEMU_HOME \"$source_path\"" >> $config_host_mak
+  echo "#define PROJECT_HOME \"$proj_path\"" >> $config_host_mak
+  echo "#define TAINT_ENABLED 1" >> $config_host_mak
+  echo "#define DEFINE_BLOCK_BEGIN" >> $config_host_mak
+  echo "#define DEFINE_INSN_BEGIN" >> $config_host_mak    
+  echo "#define DEFINE_INSN_END" >> $config_host_mak    
+  echo "#define DEFINE_EIP_TAINTED" >> $config_host_mak    
+  echo "#define TAINT_FLAGS 1" >> $config_host_mak    
+  echo "#define PRECISE_EFLAGS" >> $config_host_mak
+  echo "#define PLUGIN_TRACECAP" >> $config_host_mak
+ 
+else
+  echo "Error: The specified project is not found" 
+  exit 1
+fi
+
 if [ "$docs" = "yes" ] ; then
   echo "BUILD_DOCS=yes" >> $config_host_mak
 fi
@@ -5115,6 +5171,9 @@ esac
 
 mkdir -p $target_dir
 echo "# Automatically generated by configure - do not modify" > $config_target_mak
+
+echo "include ../config-host.mak" >> $config_target_mak
+
 
 bflt="no"
 interp_prefix1=`echo "$interp_prefix" | sed "s/%M/$target_name/g"`
